### ISSUE TITLE
好多bug.

### ISSUE THREAD

**Issue by shaoting0730** [gzfgeh/RefreshList#2]
使用你的demo.会发生bug:如图

<img width="322" alt="23" src="https://user-images.githubusercontent.com/14305431/27068696-d5246cd6-5043-11e7-82a6-9d5e83032e60.png">
<img width="354" alt="245" src="https://user-images.githubusercontent.com/14305431/27068712-e5c74ed2-5043-11e7-9a63-4f6653e3bc4a.png">

**Comment by JohnDn** [comment]
我也是这个问题 你解决了吗

**Comment by shaoting0730** [comment]
没有，放弃了该库
